/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyIndexRouteImport } from './routes/survey.index'
import { Route as SurveyNewRouteImport } from './routes/survey.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIndexRoute = SurveyIndexRouteImport.update({
  id: '/survey/',
  path: '/survey/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyNewRoute = SurveyNewRouteImport.update({
  id: '/survey/new',
  path: '/survey/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/survey/new': typeof SurveyNewRoute
  '/survey/': typeof SurveyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/survey/new': typeof SurveyNewRoute
  '/survey': typeof SurveyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/survey/new': typeof SurveyNewRoute
  '/survey/': typeof SurveyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/survey/new' | '/survey/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/survey/new' | '/survey'
  id: '__root__' | '/' | '/survey/new' | '/survey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SurveyNewRoute: typeof SurveyNewRoute
  SurveyIndexRoute: typeof SurveyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/': {
      id: '/survey/'
      path: '/survey'
      fullPath: '/survey/'
      preLoaderRoute: typeof SurveyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/new': {
      id: '/survey/new'
      path: '/survey/new'
      fullPath: '/survey/new'
      preLoaderRoute: typeof SurveyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SurveyNewRoute: SurveyNewRoute,
  SurveyIndexRoute: SurveyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
